org.gradle.jvmargs=-Xmx2048M
loom.ignoreDependencyLoomVersionValidation=true
##
minecraft_version=1.20.1
enabled_platforms=fabric,forge
architectury_version=9.1.12
parchment_version=1.20.1:2023.09.03
forge_version=1.20.1-47.2.1
## Mod Properties
mod_id=scholar
mod_name=Scholar
mod_license=GNU GPLv3
mod_version=1.1.10
mod_maven_group=io.github.mortuusars.scholar
mod_authors=mortuusars
mod_description=Book improvements: two-page view, lectern editing, colored books, QOL-features
mod_page=https://www.curseforge.com/minecraft/mc-mods/scholar
mod_github=https://github.com/mortuusars/Scholar
mod_issues=https://github.com/mortuusars/Scholar/issues
mod_curseforge_project_id=961802
mod_modrinth_project_id=fX4dIQCo
## Dependency Versions
minecraft_version_range=[1.20.1,1.20.2)
forge_version_range=[47,)
loader_version_range=[47,)
fabric_loader_version=0.16.10
fabric_api_version=0.92.2+1.20.1
forge_config_api_version=8.0.0
mixinextras_version=0.4.1
# Mod Versions
jei_version=15.2.0.22
