architectury {
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/scholar.accesswidener")
}

configurations {
    create("junit")
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:${forge_config_api_port_version}"

//    modCompileOnlyApi("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")

    // Needed for mixin to fix formatting key conflicts
    modCompileOnly("mezz.jei:jei-${minecraft_version}-common:${jei_version}")
    modCompileOnly("mezz.jei:jei-${minecraft_version}-gui:${jei_version}")

    // modCompileOnly("maven.modrinth:more-chiseled-bookshelf-variants:Mv3952ns")
    // modCompileOnly("curse.maven:woodster-869951:6425772")

    testImplementation(platform("org.junit:junit-bom:${project.property("jupiterVersion")}"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    "junit"(platform("org.junit:junit-bom:${project.property("jupiterVersion")}"))
    "junit"("org.junit.jupiter:junit-jupiter")
}

tasks {
    test {
        useJUnitPlatform()
    }
}